### ISSUE TITLE
Create organiser panes for Alert Windows

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/lesco#21]
We will organise Alert Windows within an Alert Wall pane (bottom-left of screen)

Eventually it will be possible to collapse these panes, but it doens't look easy in Golden Layouts.

Could you create the Alert Wall and put the relevant controls into them.

**Comment by Morphexe** [comment]
@IanMayo  I will try to find a way to collapse the panels.

**Comment by IanMayo** [comment]
@Morphexe the ability to have a parent for each type of window (Alert Windows and Data Views) is more important than collapsing the panels.

I've demoted the "collapse panels" to a future task, a costed extra.

**Comment by IanMayo** [comment]
@Morphexe - change of plan. We won't have a holder for the data views, they will continue to be free to go anywhere. We will just create an Alert Wall to contain the Alert Windows

**Comment by IanMayo** [comment]
done
