### ISSUE TITLE
Introduce main map controls

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/lesco#29]
Add some drop-down controls to the main map.

![map_1](https://cloud.githubusercontent.com/assets/1108513/18232686/1a11c596-72cd-11e6-89dd-bfa4273e9ae2.png)

![map_2](https://cloud.githubusercontent.com/assets/1108513/18232685/19fddef0-72cd-11e6-9601-7841a715cec8.png)

**Comment by Morphexe** [comment]
#40 Handles all of these.
