### ISSUE TITLE
Integrate search form

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/lesco#4]
Could you consider if we can include it as dynamic html?

If we can't, then a screenshot will do

**Comment by IanMayo** [comment]
@Morphexe  - I'm not sure about your intended sequence, but I could do with this search control next, please.  I need to produce some screenshots in the proposal.

**Comment by IanMayo** [comment]
Note - there are two buttons on the form.

Could you position them along the bottom-right corner?
![top_form](https://cloud.githubusercontent.com/assets/1108513/18225089/c3f03fca-71e2-11e6-9799-ee5b76614d8c.png)

**Comment by Morphexe** [comment]
Already working on it!

**Comment by Morphexe** [comment]
[Image](https://i1.someimage.com/diu2Z1h.png) like this ?

**Comment by IanMayo** [comment]
@Morphexe - I'd like to request some changes:
- [ ] start off with a single (empty) rule present
- [x] is the "Group" border invisible?  If I click on "+Rule" or "+Group" the added items seem identical.
- [x] if possible, could you connect the logic so that we get different operations for different data-types?  I'd expect "Is a developer" to offer some yes/no criteria
- [x] Aah, I see we've used the npmjs one.  The [GitHub](https://github.com/fubhy/react-query-builder) one is more attractive, and it seems more capable (the above operation types work).  I don't mind if you include the sources direct in our project.

Later additions:
- [ ] Use successively darker grey shades, rather than yellow
- [ ] Make AND, +Rule, +Group the same height.
- [ ] Introduce white-space to left of Search Pane, to contain logo (logo.png in repo master). Resized to 100px tall

**Comment by Morphexe** [comment]
Ok the Github one, I can't compile it, spend the last hour trying, although this one after reading the api, is able to do what we want and much simpler to use.

**Comment by IanMayo** [comment]
Ok, you've completed three of the sub-tasks, one left (start with rule present).

Will add some more items to the list.

**Comment by Morphexe** [comment]
I think I am done with all of those.
Although, like I said, we might need to look into the css on lower sizes. or perhaps we should define a min width for the search tab.

**Comment by IanMayo** [comment]
Could you provide a "Location" special search criteria. It should provide these options:
![concept development 2](https://cloud.githubusercontent.com/assets/1108513/18227581/23a33204-7221-11e6-8d33-9ff909a7881d.png)

Note that the last two items represent child lists.  If you're able to provide them, great. Else I'll fiddle with them.

**Comment by Morphexe** [comment]
Ok, so submenus are sort difficult to implement on this context with creating a custom control, although I think I came pretty close without wasting valueable time.
Check  [this](https://i1.someimage.com/MEyycLx.gifl)

**Comment by IanMayo** [comment]
Hmm. No, the operation happen one level higher. We don't have "in". We have a some operators. Most don't have children. The last few do.
