### ISSUE TITLE
Introduce "Priority" for Alert Windows

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/lesco#43]
The user should be able to specify the priority when adding a new window

**Comment by Morphexe** [comment]
This Pull request is important, since it also fixes a major bug with the mainlayout, where I was not unmounting the GoldenLayout, which in turn broke the routing, and created a  (right now, small memory leak).

**Comment by IanMayo** [comment]
@Morphexe  You haven't submitted a PR for the above commit  yet, have you?

**Comment by IanMayo** [comment]
done
