### ISSUE TITLE
JS Walkthrough

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/lesco#52]
Could you research a JS Walkthrough library?

You know, the user goes into the demo, and we popup little dialogs to lead them through the app, and we instruct them to do things.  If you create the first couple then I can fill in the rest.

**Comment by Morphexe** [comment]
@IanMayo  This seems what you want ? 

http://introjs.com/

This is comercial licensed one :| and I am not sure how easy this ewoud be to implement in our current project.

**Comment by IanMayo** [comment]
Sorry, we're still Open Source only.

**Comment by Morphexe** [comment]
@IanMayo So I have created a sample walkthough for the search window. 
I still need to figure out how to continue the Tutorial on a different window.(Map, Alerts , etc) without starting them all at the same time.

**Comment by IanMayo** [comment]
@Morphexe  Great progress so far.

**Comment by IanMayo** [comment]
@Morphexe - more walkthrough feedback

## Search form
- [x] Start off by pointing out the help button, that will take the user to the user guide
- [x] Get the user to add a new rule, and specify data in the last hour (Time, Last, 1 hour)

## Create data view
- [x] Explain that the data can be shown in a new view, or added to an existing one
- [ ] At the end, when I press confirm, a new view isn't created.  I'm sure that did work.

## Table-based alert view
- [ ] I don't know if you can sort the logic or not, but it would be good to also create an alert view like this:
- [ ] Get user to zoom in on London
- [ ] Change location criteria to Current Viewport
- [ ] remove time filteer
- [ ] Specify facebook as source
- [ ] create alert view (priority 1)
- [ ] show new alert view  (with dynamic updates - but that's for another issue :-) )

**Comment by IanMayo** [comment]
done
