### ISSUE TITLE
Create Table control

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/lesco#6]
We need a panel with a table.  If you insert some dummy titles, text in rows,  then I'll edit to populate them.

**Comment by IanMayo** [comment]
We've got some growing ideas for map controls.  

Once they're ready, I'd like you to start adding them to the map, please.

**Comment by Morphexe** [comment]
So the  Table View Looks like this with some dummy data [Table View](https://i1.someimage.com/66mvfqC.png)
