### ISSUE TITLE
Customize alert window title bar

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/lesco#8]
Introduce:
- color for the title bar (there's an example in the Golden-Layouts demo). The color will be for the title, not the window itself.
- mute button
- drop-down menu

Other controls as recorded in the [concept development document](https://docs.google.com/document/d/1LgrP4kCgLNtXJxasJT_KGAA_sfmWrOFe9BSXwwRecRQ/edit#bookmark=id.xw5bcgbwj7tx): 

It will be valuable to have the drop-down to change Priority (1-Highest to 5-Lowest).

It will also be valuable to have "Export to CSV" and "Export to PNG" commands on the drop-down.

**Comment by Morphexe** [comment]
I have already added the mute/unmute button, and cogwheel to be used as dropdown (although the DropDown itself is still not implemented)

**Comment by IanMayo** [comment]
Hmm, I think you need to push it.

**Comment by Morphexe** [comment]
[This ](https://i1.someimage.com/A4cohyZ.png)what it looks like right now :
